### ISSUE TITLE
Dead Command

### ISSUE THREAD

**Issue by Denomix** [xShadqt/Serifix#1]
The tackle command appears to have been broken at some point. Some people in the discord im in brought it up to me, i tested it out in my server that is slowly filling up with bots, and sure enough, nothing happens. I dont know when it stopped working.

**Comment by xShadqt** [comment]
Hi, Denomix!
I'm super stoked that you are using Serifix in your server. Serifix is currently in rewrite stages. The following categories may be super weird: utility, information (which is being worked on as we speak). Thank you for using this as a way to list our issues. Please DM me ( shadat.#3550 ) if you have any more concerns or questions.

**Comment by xShadqt** [comment]
Another possible reason, I may have been working on the bot at that time so when the bot was restarting, the command did not go through.
